//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevelopmentEntities : DbContext
    {
        public DevelopmentEntities()
            : base("name=DevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Input> Inputs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Method> Methods { get; set; }
        public virtual DbSet<Output> Outputs { get; set; }
    }
}
