//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Output
    {
        public int ItemId { get; set; }
        public int MethodId { get; set; }
        public int Qty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Method Method { get; set; }
    }
}
